input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "environment" => "development"
      "project" => "leave-management-system"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "lms-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}